---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbday
  labels:
    app.kubernetes.io/name: kbday
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kbday
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kbday
    spec:
      containers:
        - name: kbday
          image: kbday
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
